

module.exports = [
{"Date": "24 Sep 2015", "Description": "Teds", "Amount": 38.50, "Category": "Utilities"},
{"Date": "24 Sep 2015", "Description": "Tesco", "Amount": 7.97, "Category": "Food"},
{"Date": "23 Sep 2015", "Description": "Tesco", "Amount": 10.30, "Category": "Food"},
{"Date": "22 Sep 2015", "Description": "Tesco", "Amount": 4.38, "Category": "Food"},
{"Date": "22 Sep 2015", "Description": "Waitrose", "Amount": 2.91, "Category": "Food"},
{"Date": "21 Sep 2015", "Description": "Netflix", "Amount": 5.99, "Category": "Entertainment"},
{"Date": "18 Sep 2015", "Description": "Tesco", "Amount": 2.48 , "Category": "Food"},
{"Date": "22 Sep 2015", "Description": "Tesco", "Amount": 6.07, "Category": "Food"},
{"Date": "24 Sep 2015", "Description": "CO-OP", "Amount": 6.10, "Category": "Food"},
{"Date": "24 Sep 2015", "Description": "STARBUCKS", "Amount": 10.00, "Category": "Food"},
{"Date": "21 Sep 2015", "Description": "BOOTS THE CHEMIST LONDON", "Amount":11.24, "Category":"Medical"},
{"Date": "21 Sep 2015", "Description": "CO-OP - ST PAULS LONDON", "Amount":6.10, "Category":"Groceries"},
{"Date": "20 Sep 2015", "Description": "TESCO SELF SERVICE LONDON", "Amount":7.77, "Category":"Groceries"},
{"Date": "19 Sep 2015", "Description": "HOLLAND & BARRETT CANAR LONDON", "Amount":41.98, "Category":"Groceries"},
{"Date": "19 Sep 2015", "Description": "SUPERDRY CANARY WHARF LONDON", "Amount":19.99, "Category":"Clothing"},
{"Date": "19 Sep 2015", "Description": "TESCO SELF SERVICE LONDON", "Amount":10.46, "Category":"Groceries"},
{"Date": "19 Sep 2015", "Description": "THREE-TOP UP (HS) GLASGOW", "Amount":20.00, "Category":"Communications"},
{"Date": "18 Sep 2015", "Description": "BAR 38 (INDIA QUAY) LONDON", "Amount":11.40, "Category":"Alcohol"},
{"Date": "18 Sep 2015", "Description": "BAR 38 (INDIA QUAY) LONDON", "Amount":12.10, "Category":"Alcohol"},
{"Date": "18 Sep 2015", "Description": "THE PARLOUR LONDON", "Amount":10.20, "Category":"Alcohol"},
{"Date": "18 Sep 2015", "Description": "UBER UBER LONDON", "Amount":18.72, "Category":"Travel"},
{"Date": "18 Sep 2015", "Description": "ZARA CANARY WARF UNIT 9 LONDON", "Amount":39.99, "Category":"Clothing"},
{"Date": "17 Sep 2015", "Description": "CO-OP - CANARY WHARF CANARY WHARF", "Amount":7.09, "Category":"Groceries"},
{"Date": "17 Sep 2015", "Description": "TFL", "Amount":123.30, "Category":"Travel"},
{"Date": "17 Sep 2015", "Description": "Cosmopolitan Fashion Fest", "Amount":10.00, "Category":"Alcohol"},
{"Date": "16 Sep 2015", "Description": "CINEWORLD CINEMAS ECOM LONDON", "Amount":24.40, "Category":"Entertainment"},
{"Date": "16 Sep 2015", "Description": "TESCO SELF SERVICE LONDON", "Amount":5.58, "Category":"Groceries"},
{"Date": "16 Sep 2015", "Description": "TESCO SELF SERVICE LONDON", "Amount":1.64, "Category":"Groceries"},
{"Date": "16 Sep 2015", "Description": "THE PARLOUR LONDON", "Amount":10.20, "Category":"Alcohol"},
{"Date": "16 Sep 2015", "Description": "THE PARLOUR LONDON", "Amount":10.85, "Category":"Alcohol"},
{"Date": "15 Sep 2015", "Description": "CO-OP - CANARY WHARF CANARY WHARF", "Amount":7.59, "Category":"Groceries"},
{"Date": "15 Sep 2015", "Description": "STARBUCKS CARD RELOA 8452703310", "Amount":30.00, "Category":"Groceries"},
{"Date": "15 Sep 2015", "Description": "TESCO SELF SERVICE LONDON", "Amount":7.27, "Category":"Groceries"},
{"Date": "14 Sep 2015", "Description": "TESCO SELF SERVICE LONDON", "Amount": 866.00, "Category":"Rent"},
{"Date": "14 Sep 2015", "Description": "CO-OP - CANARY WHARF CANARY WHARF", "Amount":3.98, "Category":"Groceries"},
{"Date": "14 Sep 2015", "Description": "YPLAN YPLANAPP.COM", "Amount":55.00, "Category":"Entertainment"},
{"Date": "23 Sep 2015", "Description": "iTunes", "Amount":46.77, "Category":"Entertainment"},
{"Date": "22 Sep 2015", "Description": "River Island", "Amount":28.00, "Category":"Clothing"},
{"Date": "19 Sep 2015", "Description": "iTunes", "Amount":1.58, "Category":"Entertainment"}
];

